name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make
        run: make

  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          echo "3" | make run

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3    

      - name: Cache Google Test
        uses: actions/cache@v2
        with:
         path: /usr/local/lib/libgtest*
         key: ${{ runner.os }}-googletest
        
      - name: Download and Build Google Test
        run: |
          if [ ! -f /usr/local/lib/libgtest_main.a ]; then
            git clone https://github.com/google/googletest.git
            cd googletest
            cmake .
            make
            sudo make install
          fi

      - name: Test
        run: make test


